- name: Learn ANSIBLE
  hosts: localhost
  connection: true

  become: true
  var:
    x:10
  tasks:
    - name: Determine which is higher
      when: x > 10
      ansible.builtin.debug:
          msg: X is greater

    - name: Determine which is higher
      when: x < 10
      ansible.builtin.debug:
        msg: X is lesser





